"""
Dynamic Mixture of Experts (DynamicMoE) model.
Orchestrates Shared Encoder, Dynamic Router, and Experts with dynamic expansion capabilities.
"""

import copy
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional, Dict, Any, List

from .encoder import SharedEncoder, EMAEncoder
from .router import DynamicRouter
from .expert import MLPExpert


class DynamicMoE(nn.Module):
    """
    Dynamic MoE Architecture:
        y = sum_{i in top-k} g_i(x) * E_i(h(x))
    where h(x) is generated by a shared encoder, g(x) is determined by DynamicRouter,
    and E_i are dynamically managed experts.
    """

    def __init__(
        self,
        encoder: SharedEncoder,
        router: DynamicRouter,
        experts: List[MLPExpert],
        use_ema_encoder: bool = True,
        ema_decay: float = 0.99,
    ):
        super().__init__()
        self.encoder = encoder
        self.router = router
        self.experts = nn.ModuleList(experts)

        self.use_ema_encoder = use_ema_encoder
        if use_ema_encoder:
            self.ema_encoder = EMAEncoder(encoder, decay=ema_decay)
        else:
            self.ema_encoder = None

        assert len(self.experts) == self.router.num_experts, (
            f"Expert count mismatch: {len(self.experts)} experts vs {self.router.num_experts} router heads"
        )

    @property
    def num_experts(self) -> int:
        return len(self.experts)

    def forward(
        self,
        x: Optional[torch.Tensor] = None,
        top_k: Optional[int] = None,
        return_routing_info: bool = False,
        latent_h: Optional[torch.Tensor] = None,
    ) -> torch.Tensor | tuple[torch.Tensor, Dict[str, Any]]:
        """
        Forward pass with sparse top-k mixture.
        If latent_h is provided, bypasses the encoder (useful for Latent Replay).
        """
        if latent_h is not None:
            h = latent_h
        else:
            assert x is not None, "Either x or latent_h must be provided."
            h = self.encoder(x)
        routing_weights, topk_idx, router_logits = self.router(h, top_k=top_k)

        batch_size = h.size(0)
        num_classes = self.experts[0].num_classes
        out = torch.zeros(batch_size, num_classes, device=h.device, dtype=h.dtype)

        # Efficient sparse dispatch: only execute experts selected in the batch
        unique_experts = torch.unique(topk_idx)
        expert_outputs_dict = {}

        for exp_idx_t in unique_experts:
            exp_idx = exp_idx_t.item()
            # Find batch samples where this expert is among top-k
            mask = (topk_idx == exp_idx).any(dim=-1)
            if mask.any():
                h_sub = h[mask]
                exp_out = self.experts[exp_idx](h_sub)
                g_sub = routing_weights[mask, exp_idx].unsqueeze(-1)
                out[mask] += g_sub * exp_out
                if return_routing_info:
                    expert_outputs_dict[exp_idx] = exp_out

        if return_routing_info:
            entropy = self.router.compute_entropy(routing_weights)
            routing_info = {
                "h": h,
                "routing_weights": routing_weights,
                "topk_idx": topk_idx,
                "router_logits": router_logits,
                "entropy": entropy,
                "expert_outputs": expert_outputs_dict,
            }
            return out, routing_info

        return out

    def get_routing_features(self, x: torch.Tensor) -> torch.Tensor:
        """
        Returns routing representations: uses EMA encoder if enabled, else online encoder.
        """
        if self.ema_encoder is not None:
            return self.ema_encoder(x)
        with torch.no_grad():
            return self.encoder(x)

    def update_ema_encoder(self) -> None:
        if self.ema_encoder is not None:
            self.ema_encoder.update(self.encoder)

    def get_all_expert_outputs(self, h: torch.Tensor) -> torch.Tensor:
        """
        Evaluates all experts on representation h: [batch_size, num_experts, num_classes].
        Optimized via torch.func.vmap to avoid O(N) kernel launch overhead.
        """
        if not self.experts:
            return torch.empty(h.size(0), 0, 0, device=h.device)

        # Optimization: use vmap for O(1) kernel launch batched forward pass
        try:
            from torch.func import stack_module_state, functional_call, vmap

            params, buffers = stack_module_state(self.experts)

            def fmodel(p, b, x):
                return functional_call(
                    self.experts[0], (p, b), (x,), kwargs={"track_usage": False}
                )

            batched_forward = vmap(fmodel, in_dims=(0, 0, None))
            out = batched_forward(params, buffers, h)  # [E, B, C]
            return out.transpose(0, 1)  # [B, E, C]
        except Exception:
            # Fallback loop
            outputs = []
            for expert in self.experts:
                outputs.append(expert(h, track_usage=False))
            return torch.stack(outputs, dim=1)

    def add_expert(
        self,
        new_expert: MLPExpert,
        parent_id: Optional[int] = None,
        prototype_feat: Optional[torch.Tensor] = None,
        null_space_basis: Optional[torch.Tensor] = None,
    ) -> int:
        """
        Adds a new expert to the pool and expands the router.
        null_space_basis: historical prototype centroids used to orthogonally anchor
        the new routing row so it cannot overlap historical routing regions.
        """
        new_id = len(self.experts)
        new_expert.expert_id = new_id
        self.experts.append(new_expert)
        self.router.add_expert(
            parent_id=parent_id,
            prototype_feat=prototype_feat,
            null_space_basis=null_space_basis,
        )
        return new_id

    def prune_expert(
        self, prune_idx: int, prototype_memory: Optional[Any] = None
    ) -> None:
        """
        Prunes the expert at prune_idx, updates router, and synchronizes prototype memory.
        """
        assert 0 <= prune_idx < len(self.experts)
        assert len(self.experts) > 1, "Cannot prune only remaining expert"

        if prototype_memory is not None:
            prototype_memory.sync_on_prune(prune_idx)

        del self.experts[prune_idx]
        self.router.prune_expert(prune_idx)

        # Re-index remaining experts
        for i, expert in enumerate(self.experts):
            expert.expert_id = i

    def merge_experts(
        self, idx1: int, idx2: int, prototype_memory: Optional[Any] = None
    ) -> int:
        """
        Merges expert idx2 into idx1 via parameter averaging, updates router,
        and synchronizes historical prototype distributions.
        """
        assert (
            0 <= idx1 < len(self.experts)
            and 0 <= idx2 < len(self.experts)
            and idx1 != idx2
        )
        e1, e2 = self.experts[idx1], self.experts[idx2]

        with torch.no_grad():
            # Average fc1 and fc2
            for p1, p2 in zip(e1.fc1.parameters(), e2.fc1.parameters()):
                p1.data.add_(p2.data).mul_(0.5)
            for p1, p2 in zip(e1.fc2.parameters(), e2.fc2.parameters()):
                p1.data.add_(p2.data).mul_(0.5)
            e1.usage_count.add_(e2.usage_count)

        if prototype_memory is not None:
            prototype_memory.sync_on_merge(idx1, idx2)

        # Pruning router and list without duplicate prototype sync
        self.prune_expert(idx2, prototype_memory=None)
        return idx1

    def freeze_historical_experts(self, leave_unfrozen: int = 1) -> None:
        """
        Freezes all experts except the last `leave_unfrozen` experts.
        Also locks their corresponding routing paths in the router.
        """
        num_to_freeze = max(0, self.num_experts - leave_unfrozen)
        for i in range(num_to_freeze):
            for param in self.experts[i].parameters():
                param.requires_grad = False

        # Lock router gradients for the frozen experts
        self.router.lock_historical_routing(num_to_freeze)

    def unfreeze_all_experts(self) -> None:
        """Unfreezes all experts and router paths for joint calibration."""
        for exp in self.experts:
            for param in exp.parameters():
                param.requires_grad = True
        self.router.lock_historical_routing(0)

    def unfreeze_experts_keep_routing_lock(self) -> None:
        """
        Unfreezes ALL experts (so historical experts can learn the negative
        boundaries of other tasks during joint calibration) while KEEPING the
        historical routing rows locked. Only the newest router row adapts, so
        old-task inputs keep being routed to their original experts.
        """
        for exp in self.experts:
            for param in exp.parameters():
                param.requires_grad = True
        self.router.lock_historical_routing(max(0, self.num_experts - 1))


# PAL-MoE alias
PALMoE = DynamicMoE
