"""
Dynamic Mixture of Experts (DynamicMoE) model.
Orchestrates Shared Encoder, Dynamic Router, and Experts with dynamic expansion capabilities.
"""

from typing import Any, Optional

import torch
import torch.nn as nn

from .encoder import EMAEncoder, SharedEncoder
from .expert import MLPExpert
from .router import DynamicRouter


class DynamicMoE(nn.Module):
    """
    Dynamic MoE Architecture:
        y = sum_{i in top-k} g_i(x) * E_i(h(x))
    where h(x) is generated by a shared encoder, g(x) is determined by DynamicRouter,
    and E_i are dynamically managed experts.
    """

    def __init__(
        self,
        encoder: SharedEncoder,
        router: DynamicRouter,
        experts: list[MLPExpert],
        use_ema_encoder: bool = True,
        ema_decay: float = 0.99,
    ):
        super().__init__()
        self.encoder = encoder
        self.router = router
        self.experts = nn.ModuleList(experts)

        self.use_ema_encoder = use_ema_encoder
        if use_ema_encoder:
            self.ema_encoder = EMAEncoder(encoder, decay=ema_decay)
        else:
            self.ema_encoder = None

        # Optional prototype-anchored inference routing (see set_prototype_routing)
        self.prototype_memory = None
        self.proto_routing_alpha = 0.0
        self.proto_routing_threshold = None

        assert (
            len(self.experts) == self.router.num_experts
        ), f"Expert count mismatch: {len(self.experts)} experts vs {self.router.num_experts} router heads"

    @property
    def num_experts(self) -> int:
        return len(self.experts)

    def set_prototype_routing(
        self,
        prototype_memory: Any,
        alpha: float = 0.5,
        threshold: Optional[float] = None,
    ) -> None:
        """
        Enables prototype-anchored inference routing.

        At inference time (model.eval()), each input is routed as
            g_final = (1 - alpha * conf) * g_router + alpha * conf * r_p(nearest)
        where `conf = clamp(1 - d1/d2, 0, 1)` is a threshold-free nearest-class-mean
        confidence: d1 is the distance to the nearest stored prototype, d2 the
        distance to the nearest prototype of a different task. Close, unambiguous
        inputs inherit their prototype's historical routing distribution; distant
        or ambiguous inputs keep the learned router. If memory holds prototypes of
        a single task there is no cross-task ambiguity and `conf = 1`. Training is
        untouched.
        """
        self.prototype_memory = prototype_memory
        self.proto_routing_alpha = float(alpha)
        self.proto_routing_threshold = threshold

    def set_expert_temperatures(self, temperatures: Optional[torch.Tensor]) -> None:
        """
        Optional per-expert logit temperatures (runtime attribute, shape [N]).

        Used by `pal_moe.evaluation.calibration.calibrate_expert_temperatures`
        to make top-k>1 mixing and confidence estimates better calibrated. It is
        intentionally not a registered buffer so existing state dicts keep
        loading; callers that persist models must save the tensor themselves.
        """
        self.expert_temperatures = temperatures

    @torch.no_grad()
    def calibrate_prototype_routing(
        self,
        grid: tuple[float, ...] = (0.0, 0.25, 0.5, 0.75, 1.0, 1.25),
    ) -> float:
        """
        Picks the prototype-anchoring weight `alpha` by accuracy on the stored
        latent exemplars (zero raw data, no training).

        Returns the selected alpha and leaves `proto_routing_alpha` at it.
        """
        mem = self.prototype_memory
        if mem is None or mem.is_empty():
            return self.proto_routing_alpha
        device = next(self.parameters()).device
        batch = mem.get_exemplar_batch(device)
        if batch is None:
            return self.proto_routing_alpha
        x, y = batch
        was_training = self.training
        self.eval()
        best_alpha, best_acc = self.proto_routing_alpha, -1.0
        for alpha in grid:
            self.proto_routing_alpha = float(alpha)
            acc = (self(latent_h=x).argmax(dim=-1) == y).float().mean().item()
            if acc > best_acc:
                best_acc, best_alpha = acc, float(alpha)
        self.proto_routing_alpha = best_alpha
        self.train(was_training)
        return best_alpha

    @torch.no_grad()
    def _prototype_routing_anchor(
        self, h: torch.Tensor
    ) -> Optional[tuple[torch.Tensor, torch.Tensor]]:
        """
        Returns (anchors [B, N], confidence [B, 1]) from a k-NN vote over the
        stored prototypes.

        The anchor distribution is a distance-weighted vote of the k nearest
        prototypes' expert anchors (explicit owner experts when available):
            w_p   = softmax(-d_p / d1)          (scale-free kernel, d1 = nearest)
            A     = sum_p w_p * anchor_p
        Single-nearest-neighbour assignment is too brittle when task regions
        overlap, so the soft vote is kept.

        The trust weight is the threshold-free nearest-class-mean margin on the
        raw distances: `conf = clamp(1 - d1/d2, 0, 1)` with d1 the nearest
        prototype and d2 the nearest prototype of a DIFFERENT task. Equidistant
        (ambiguous) inputs get conf -> 0 and keep the learned router, while
        inputs that are clearly inside one task's region get conf -> 1.
        """
        mem = self.prototype_memory
        if mem is None or mem.is_empty():
            return None
        v_mat = mem.get_prototype_matrix(h.device)
        if v_mat is None:
            return None
        a_mat = mem.get_expert_anchor_matrix(self.num_experts, h.device)
        if a_mat is None:
            return None

        dists = torch.cdist(h, v_mat)  # [B, P]
        k = min(8, v_mat.size(0))
        d_k, idx_k = torch.topk(dists, k=k, dim=-1, largest=False)  # [B, k]

        tau = d_k[:, 0].clamp(min=1e-6).unsqueeze(-1)
        weights = torch.softmax(-d_k / tau, dim=-1)  # [B, k]
        anchors = torch.einsum("bk,bkn->bn", weights, a_mat[idx_k])  # [B, N]

        # NCM confidence on the raw distances (see docstring): d1 = nearest
        # prototype, d2 = nearest prototype of a different task. When memory
        # only knows one task there is no competing region (d2 = inf -> conf 1);
        # exactly equidistant neighbours give a 0/0 ratio -> conf 0.
        d1, nearest_idx = dists.min(dim=1)
        task_ids = mem.get_task_id_vector(h.device)  # [P]
        same_task = task_ids.unsqueeze(0) == task_ids[nearest_idx].unsqueeze(1)
        d2 = dists.masked_fill(same_task, float("inf")).min(dim=1).values
        ratio = torch.nan_to_num(d1 / d2, nan=1.0, posinf=0.0)
        confidence = (1.0 - ratio).clamp(min=0.0, max=1.0)

        if self.proto_routing_threshold is not None:
            close = (d_k[:, 0] <= self.proto_routing_threshold).float()
            confidence = confidence * close

        return anchors, confidence.unsqueeze(-1)

    def _route(
        self,
        h: torch.Tensor,
        top_k: Optional[int] = None,
        need_logits: bool = False,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Routing dispatch. Uses prototype anchoring in eval mode when enabled,
        otherwise the learned router. `need_logits` avoids the extra router call
        when routing information is not requested.
        """
        use_anchor = (
            not self.training
            and self.prototype_memory is not None
            and self.proto_routing_alpha > 0
        )
        if use_anchor:
            anchor = self._prototype_routing_anchor(h)
            if anchor is not None:
                anchors, confidence = anchor
                dense = self.router.get_full_distribution(h)
                weight = self.proto_routing_alpha * confidence
                dense = (1.0 - weight) * dense + weight * anchors
                k = top_k if top_k is not None else self.router.top_k
                k = min(k, self.router.num_experts)
                topk_probs, topk_idx = torch.topk(dense, k=k, dim=-1)
                if k > 1:
                    topk_probs = topk_probs / (
                        topk_probs.sum(dim=-1, keepdim=True) + 1e-9
                    )
                routing_weights = torch.zeros_like(dense).scatter_(
                    -1, topk_idx, topk_probs
                )
                if need_logits:
                    _, _, router_logits = self.router(h, top_k=top_k)
                else:
                    router_logits = dense
                return routing_weights, topk_idx, router_logits
        return self.router(h, top_k=top_k)

    def forward(
        self,
        x: Optional[torch.Tensor] = None,
        top_k: Optional[int] = None,
        return_routing_info: bool = False,
        latent_h: Optional[torch.Tensor] = None,
    ) -> torch.Tensor | tuple[torch.Tensor, dict[str, Any]]:
        """
        Forward pass with sparse top-k mixture.
        If latent_h is provided, bypasses the encoder (useful for Latent Replay).
        """
        if latent_h is not None:
            h = latent_h
        else:
            assert x is not None, "Either x or latent_h must be provided."
            h = self.encoder(x)
        routing_weights, topk_idx, router_logits = self._route(
            h, top_k=top_k, need_logits=return_routing_info
        )

        batch_size = h.size(0)
        num_classes = self.experts[0].num_classes
        out = torch.zeros(batch_size, num_classes, device=h.device, dtype=h.dtype)

        # Efficient sparse dispatch: only execute experts selected in the batch.
        # One host sync for the whole list instead of one .item() per expert.
        unique_experts = torch.unique(topk_idx).tolist()
        expert_outputs_dict = {}

        for exp_idx in unique_experts:
            # Find batch samples where this expert is among top-k
            mask = (topk_idx == exp_idx).any(dim=-1)
            if mask.any():
                h_sub = h[mask]
                exp_out = self.experts[exp_idx](h_sub)
                temps = getattr(self, "expert_temperatures", None)
                if temps is not None:
                    exp_out = exp_out / temps[exp_idx].clamp(min=1e-3)
                g_sub = routing_weights[mask, exp_idx].unsqueeze(-1)
                out[mask] += g_sub * exp_out
                if return_routing_info:
                    expert_outputs_dict[exp_idx] = exp_out

        if return_routing_info:
            entropy = self.router.compute_entropy(routing_weights)
            routing_info = {
                "h": h,
                "routing_weights": routing_weights,
                "topk_idx": topk_idx,
                "router_logits": router_logits,
                "entropy": entropy,
                "expert_outputs": expert_outputs_dict,
            }
            return out, routing_info

        return out

    def get_routing_features(self, x: torch.Tensor) -> torch.Tensor:
        """
        Returns routing representations: uses EMA encoder if enabled, else online encoder.
        """
        if self.ema_encoder is not None:
            return self.ema_encoder(x)
        with torch.no_grad():
            return self.encoder(x)

    def update_ema_encoder(self) -> None:
        if self.ema_encoder is not None:
            self.ema_encoder.update(self.encoder)

    def get_all_expert_outputs(self, h: torch.Tensor) -> torch.Tensor:
        """
        Evaluates all experts on representation h: [batch_size, num_experts, num_classes].
        Optimized via torch.func.vmap to avoid O(N) kernel launch overhead.
        """
        if not self.experts:
            return torch.empty(h.size(0), 0, 0, device=h.device)

        # Optimization: use vmap for O(1) kernel launch batched forward pass
        try:
            from torch.func import functional_call, stack_module_state, vmap

            params, buffers = stack_module_state(self.experts)

            def fmodel(p, b, x):
                return functional_call(
                    self.experts[0], (p, b), (x,), kwargs={"track_usage": False}
                )

            batched_forward = vmap(fmodel, in_dims=(0, 0, None))
            out = batched_forward(params, buffers, h)  # [E, B, C]
            out = out.transpose(0, 1)  # [B, E, C]
            temps = getattr(self, "expert_temperatures", None)
            if temps is not None:
                out = out / temps.to(out.device).clamp(min=1e-3).view(1, -1, 1)
            return out
        except (RuntimeError, NotImplementedError):
            # vmap is unavailable or the experts are not stackable; fall back
            # to the loop. Narrow on purpose: shape/device bugs must surface.
            outputs = []
            for expert in self.experts:
                outputs.append(expert(h, track_usage=False))
            return torch.stack(outputs, dim=1)

    def add_expert(
        self,
        new_expert: MLPExpert,
        parent_id: Optional[int] = None,
        prototype_feat: Optional[torch.Tensor] = None,
        null_space_basis: Optional[torch.Tensor] = None,
    ) -> int:
        """
        Adds a new expert to the pool and expands the router.
        null_space_basis: historical prototype centroids used to orthogonally anchor
        the new routing row so it cannot overlap historical routing regions.
        """
        new_id = len(self.experts)
        new_expert.expert_id = new_id
        self.experts.append(new_expert)
        self.router.add_expert(
            parent_id=parent_id,
            prototype_feat=prototype_feat,
            null_space_basis=null_space_basis,
        )
        return new_id

    def prune_expert(
        self, prune_idx: int, prototype_memory: Optional[Any] = None
    ) -> None:
        """
        Prunes the expert at prune_idx, updates router, and synchronizes prototype memory.
        """
        assert 0 <= prune_idx < len(self.experts)
        assert len(self.experts) > 1, "Cannot prune only remaining expert"

        if prototype_memory is not None:
            prototype_memory.sync_on_prune(prune_idx)

        del self.experts[prune_idx]
        self.router.prune_expert(prune_idx)

        # Re-index remaining experts
        for i, expert in enumerate(self.experts):
            expert.expert_id = i

    def merge_experts(
        self, idx1: int, idx2: int, prototype_memory: Optional[Any] = None
    ) -> int:
        """
        Merges expert idx2 into idx1 via parameter averaging, updates router,
        and synchronizes historical prototype distributions.
        """
        assert (
            0 <= idx1 < len(self.experts)
            and 0 <= idx2 < len(self.experts)
            and idx1 != idx2
        )
        e1, e2 = self.experts[idx1], self.experts[idx2]

        with torch.no_grad():
            # Average the FULL parameter set (fc1/fc2 and the residual adapter),
            # so the merged expert is the exact parameter-space midpoint.
            for p1, p2 in zip(e1.parameters(), e2.parameters()):
                p1.data.add_(p2.data).mul_(0.5)
            e1.usage_count.add_(e2.usage_count)

        if prototype_memory is not None:
            prototype_memory.sync_on_merge(idx1, idx2)

        # Merge the routing rows with the same semantics as the prototype
        # anchors (and re-attach the historical-routing lock hooks), then drop
        # the pruned expert. Previously the router row of idx2 was discarded
        # while sync_on_merge folded its prototype mass into idx1, which
        # desynchronized the gate from the stored targets.
        self.router.merge_experts(idx1, idx2)
        del self.experts[idx2]
        for i, expert in enumerate(self.experts):
            expert.expert_id = i
        return idx1

    def freeze_historical_experts(self, leave_unfrozen: int = 1) -> None:
        """
        Freezes all experts except the last `leave_unfrozen` experts.
        Also locks their corresponding routing paths in the router.
        """
        num_to_freeze = max(0, self.num_experts - leave_unfrozen)
        for i in range(num_to_freeze):
            for param in self.experts[i].parameters():
                param.requires_grad = False

        # Lock router gradients for the frozen experts
        self.router.lock_historical_routing(num_to_freeze)

    def unfreeze_all_experts(self) -> None:
        """Unfreezes all experts and router paths for joint calibration."""
        for exp in self.experts:
            for param in exp.parameters():
                param.requires_grad = True
        self.router.lock_historical_routing(0)

    def unfreeze_experts_keep_routing_lock(self) -> None:
        """
        Unfreezes ALL experts (so historical experts can learn the negative
        boundaries of other tasks during joint calibration) while KEEPING the
        historical routing rows locked. Only the newest router row adapts, so
        old-task inputs keep being routed to their original experts.
        """
        for exp in self.experts:
            for param in exp.parameters():
                param.requires_grad = True
        self.router.lock_historical_routing(max(0, self.num_experts - 1))


# PAL-MoE alias
PALMoE = DynamicMoE
